### ISSUE TITLE
"No duplicate entries were found" Ubuntu Server 18.04.1

### ISSUE THREAD

**Issue by snspinn** [davidfoerster/aptsources-cleanup#11]
Hi. I would just go ahead and perform this job manually but would like to see this working.
I ran the program as suggested but it does not find the duplicates.

![aptsourcesclean](https://user-images.githubusercontent.com/41950061/45023758-283f7900-b02f-11e8-82e1-1e0ee86423e9.PNG)

I am running this in a VM with Ubuntu Server 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64) )installed.

P.s. I tried running without the *-OEs*  flag but it would not run even after installing regex (as suggested by the error)

**Comment by davidfoerster** [comment]
Could you please add your `/etc/apt/sources.list` and `/etc/apt/sources.list.d/jenkins.list` to your issue report?

Please post text files, dialogue messages, and program output listings as text, not as images. To achieve the latter two you can either 1) select, copy & paste the dialogue text or terminal content or 2) [save the program output to a file](//askubuntu.com/q/420981/175814) and use that.
