### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Sidina-667** [davidfoerster/aptsources-cleanup#29]
I get the following when starting 0.1.7.1 or 0.1.7.2 with

```
$ sudo python3 -OEs aptsources-cleanup.zip
 File "aptsources-cleanup-0.1.7.1.zip", line 1
    PK
      ^
SyntaxError: invalid syntax
```

**Comment by davidfoerster** [comment]
Looks like a duplicate of #23 

If you have any additional information or insight I would welcome it if you added it there.
