### ISSUE TITLE
Cannot run aptsources-cleanup.pyz

### ISSUE THREAD

**Issue by t-rodriguez** [davidfoerster/aptsources-cleanup#32]
I tried to follow the instructions here: https://askubuntu.com/questions/760896/how-can-i-fix-apt-error-w-target-packages-is-configured-multiple-times

to remove the error in the title of the post. Unfortunately, I got the following error when running sudo python3 -OEs Downloads/aptsources-cleanup.pyz:

AttributeError: 'ZipInfo' object has no attribute 'is_dir'

help

**Comment by davidfoerster** [comment]
Ugh, yes. That method appeared only in Python v3.6. You’re probably running Ubuntu Xenial, aren’t you?

I’ll work on a fix.

**Comment by t-rodriguez** [comment]
Yep! I should probably upgrade.

Thanks for your quick reply. I ended up just reading a little more about
what could be wrong and then realizing the fix was fairly simple, so
already went ahead and did that on my own. So no rush :)

**Comment by davidfoerster** [comment]
Yes, it was simple indeed.
