### ISSUE TITLE
Empty files left in /etc/apt/sources.list.d/

### ISSUE THREAD

**Issue by sicherist** [davidfoerster/aptsources-cleanup#36]
I ran `sudo ./aptsources-cleanup.pyz`
and it removed 12 files that didn't contain any active repo entries.
But there are several files left in /etc/apt/sources.list.d/ that are completely empty. Shouldn't these have been also removed?

**Comment by davidfoerster** [comment]
I think `libapt` skips empty files. Thus `aptsources-cleanup` doesn’t see them.

I could implement deletion of empty files in `/etc/apt/sources.list.d/` but that seems far more complicated than a simple shell command like:

    find /etc/apt/sources.list.d -type f -empty -print -delete

Therefore I’ll close this issue report.
