### ISSUE TITLE
Use of -y does not remove files

### ISSUE THREAD

**Issue by alexbowers** [davidfoerster/aptsources-cleanup#4]
The description of `-y` is "Apply all changes without question"

however if you have an empty .list file, it does not get removed, and it prompts for a response (yes, no, all, none, display).

This should either perform no action (no) for safety, or "yes" because it was prompted to, but it should not prompt for a response.

Thanks.

**Comment by davidfoerster** [comment]
Thanks for your report! This is intentional. The flag in question only means to refer to the disablement of `deb` lines. I'm not going to offer a program option that performs a difficult to foresee destructive operation without user confirmation.

It could use a better description though.

**Comment by alexbowers** [comment]
Can we get an option to skip any other options? This is making automating the building of a vagrant box for us tricky because it hangs on waiting for the user input.

Perhaps `--skip-other-questions` or similar?

**Comment by alexbowers** [comment]
So it takes no action, but skips the question and checks completely.

**Comment by davidfoerster** [comment]
I'd prefer not to, considering that this is meant to be an interactive application. You can however

 * close stdin,
 * redirect `/dev/null` to stdin or
 * write `none` (while ensuring that the locale is English) to stdin

to skip this step.

**Comment by alexbowers** [comment]
Ok, thanks for your help, I'll figure that bit out. Thank you.
