### ISSUE TITLE
Error: Cannot find "__main__" module

### ISSUE THREAD

**Issue by AlexandruVoica** [davidfoerster/aptsources-cleanup#7]
Hello,
I've tried using your Python script and this is the error that I get:
```
/usr/bin/python3: can't find '__main__' module in './aptsources-cleanup'
```

Can you please help me?

**Comment by davidfoerster** [comment]
Smells like user error. ;-] How *exactly* did you invoke the program (command and working directory) to get this error message? What's the *full, verbatim* program output?

**Comment by jeffRowley321** [comment]
Hi, I'm also getting the same error.
command (I had to rename the file because it was named `aptsources-cleanup-0.1.7.5.2.zip`):
`sudo python3 -OEs aptsources-cleanup.zip`
directory:
`/home/usr/Downloads`
thanks for your help in advance!
